name: Demo Workflow # name of the workflow

on: # triggers of the workflow
  push: # trigger on push
    branches: # only on these branches
      - main

jobs: # jobs of the workflow

  test: # name of the job

    runs-on: ubuntu-latest # run on this machine

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python app.py

  hello:

    runs-on: ubuntu-latest # run on this machine

    steps:
      - run: echo "Hello from another job!"

  system-info:

    runs-on: ubuntu-latest

    steps:
      - run: uname -a
      - run: python --version
      - run: pwd